services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}

  postgres:
    image:  postgres:16-alpine
    container_name: vention_project_db
    environment:
      POSTGRES_USER : ${DB_USER}
      POSTGRES_PASSWORD : ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
    
  