services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - gateway
    restart: unless-stopped


  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: api_gateway
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__Key=${JWT_KEY}
      - GatewaySettings__SharedSecret=${YARP_GATEWAY_KEY}
    depends_on:
      - api

  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    # ports:
    #  - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - GatewaySettings__SharedSecret=${YARP_GATEWAY_KEY}
      - RABBITMQ_HOST=rabbitmq
    volumes:
     - ./uploads:/app/uploads

  postgres:
    image: postgres:18-alpine
    container_name: vention_project_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis: #without passwords for now and also i don't like the api enviroment configuration should check it after
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      restart: unless-stopped
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq
volumes:
  pgdata:
  redis-data:
  rabbitmq-data:
